// Package codegen emits the typed Go API from schema IR.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/eji/tiqq/schema"
)

type Config struct {
	Package string
}

// Generate emits typed tables with generic InnerJoin and LeftJoin methods.
func Generate(database schema.Schema, config Config) ([]byte, error) {
	if config.Package == "" {
		return nil, fmt.Errorf("codegen: package name is required")
	}
	tables := append([]schema.Table(nil), database.Tables...)
	sort.Slice(tables, func(i, j int) bool { return tables[i].Name < tables[j].Name })
	if err := validateForeignKeys(tables); err != nil {
		return nil, err
	}

	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by tiqq; DO NOT EDIT.\npackage %s\n\n", config.Package)
	output.WriteString("import (\n\t\"database/sql\"\n\n\t\"github.com/eji/tiqq\"\n)\n\n")
	for _, table := range tables {
		writeTable(&output, table)
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return formatted, nil
}

func validateForeignKeys(tables []schema.Table) error {
	known := make(map[string]bool, len(tables))
	for _, table := range tables {
		known[table.Name] = true
	}
	for _, table := range tables {
		for _, foreignKey := range table.ForeignKeys {
			if !known[foreignKey.ReferencedTable] {
				return fmt.Errorf("codegen: foreign key %s references unknown table %s", foreignKey.Name, foreignKey.ReferencedTable)
			}
		}
	}
	return nil
}

func writeTable(output *bytes.Buffer, table schema.Table) {
	typeName := exported(singular(table.Name))
	scope := typeName + "Scope"
	nullableType := "Nullable" + typeName + "TableDef"
	fmt.Fprintf(output, "type %s struct{}\n\ntype %sTableDef struct {\n\tref tiqq.TableRef\n", scope, typeName)
	for _, column := range table.Columns {
		fmt.Fprintf(output, "\t%s %s\n", exported(column.Name), columnType(scope, column, false))
	}
	output.WriteString("}\n\n")
	fmt.Fprintf(output, "type %s struct {\n", nullableType)
	for _, column := range table.Columns {
		fmt.Fprintf(output, "\t%s %s\n", exported(column.Name), columnType(scope, column, true))
	}
	output.WriteString("}\n\n")
	fmt.Fprintf(output, "var %sTable = %sTableDef{\n\tref: tiqq.NewTableRef(%q),\n", typeName, typeName, table.Name)
	for _, column := range table.Columns {
		sumType, avgType, numeric := numericAggregateTypes(column.DBType)
		constructor := "RequiredColumn"
		typeArguments := fmt.Sprintf("%s, %s", scope, goType(column.DBType))
		if numeric {
			constructor = "RequiredNumericColumn"
			typeArguments = fmt.Sprintf("%s, %s, %s, %s", scope, goType(column.DBType), sumType, avgType)
		}
		if column.Nullable {
			constructor = "NullableColumn"
			if numeric {
				constructor = "NullableNumericColumn"
			}
		}
		fmt.Fprintf(output, "\t%s: tiqq.%s[%s](%q, %q),\n", exported(column.Name), constructor, typeArguments, table.Name, column.Name)
	}
	output.WriteString("}\n\n")
	fmt.Fprintf(output, "func (table %sTableDef) TiqqTableInfo() tiqq.TableInfo[%sTableDef, %s] {\n", typeName, typeName, nullableType)
	fmt.Fprintf(output, "return tiqq.NewTableInfo(table.ref, table, %s{\n", nullableType)
	for _, column := range table.Columns {
		function := "RebindNullable"
		_, _, numeric := numericAggregateTypes(column.DBType)
		if numeric {
			function = "RebindNullableNumeric"
		}
		if column.Nullable {
			function = "RebindExistingNullable"
			if numeric {
				function = "RebindExistingNullableNumeric"
			}
		}
		fmt.Fprintf(output, "\t%s: tiqq.%s[%s, %s](table.%s),\n", exported(column.Name), function, scope, scope, exported(column.Name))
	}
	output.WriteString("}, []tiqq.ForeignKey{")
	for _, foreignKey := range table.ForeignKeys {
		fmt.Fprintf(output, "{Columns: %#v, ReferencedTable: %q, ReferencedColumns: %#v},", foreignKey.Columns, foreignKey.ReferencedTable, foreignKey.ReferencedColumns)
	}
	output.WriteString("})\n}\n\n")
	fmt.Fprintf(output, "func (table %sTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[%sTableDef] { return tiqq.TableJoinSource(table.TiqqTableInfo()) }\n", typeName, typeName)
	fmt.Fprintf(output, "func (table %sTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[%sTableDef, NC] { return tiqq.LeftJoin(table, right) }\n", typeName, typeName)
	fmt.Fprintf(output, "func (table %sTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[%sTableDef, C] { return tiqq.InnerJoin(table, right) }\n", typeName, typeName)
	fmt.Fprintf(output, "func (table %sTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query { return tiqq.NewTableQuery(table).Where(predicates...) }\n", typeName)
	fmt.Fprintf(output, "func (table %sTableDef) Select(columns ...tiqq.Selection) tiqq.Query { return tiqq.NewTableQuery(table).Select(columns...) }\n", typeName)
	fmt.Fprintf(output, "func (table %sTableDef) GroupBy(columns ...tiqq.Selection) tiqq.Query { return tiqq.NewTableQuery(table).GroupBy(columns...) }\n", typeName)
	fmt.Fprintf(output, "func (table %sTableDef) Update() tiqq.UpdateQuery[%s] { return tiqq.NewUpdate[%s](table) }\n", typeName, scope, scope)
	fmt.Fprintf(output, "func (table %sTableDef) Insert() tiqq.InsertQuery[%s] { return tiqq.NewInsert[%s](table.ref, %#v, %#v) }\n", typeName, scope, scope, insertableColumns(table.Columns), requiredInsertColumns(table.Columns))
	fmt.Fprintf(output, "func (table %sTableDef) As(alias string) %sTableDef {\n", typeName, typeName)
	output.WriteString("table.ref = table.ref.As(alias)\n")
	for _, column := range table.Columns {
		function := "AliasColumn"
		if _, _, numeric := numericAggregateTypes(column.DBType); numeric {
			function = "AliasNumericColumn"
		}
		fmt.Fprintf(output, "table.%s = tiqq.%s[%s, %s](table.%s, alias)\n", exported(column.Name), function, scope, scope, exported(column.Name))
	}
	output.WriteString("return table\n}\n\n")
}

func insertableColumns(columns []schema.Column) []string {
	var result []string
	for _, column := range columns {
		if !column.Generated && !column.Identity {
			result = append(result, column.Name)
		}
	}
	return result
}

func requiredInsertColumns(columns []schema.Column) []string {
	var result []string
	for _, column := range columns {
		if !column.Nullable && column.Default == nil && !column.Generated && !column.Identity {
			result = append(result, column.Name)
		}
	}
	return result
}

func columnType(scope string, column schema.Column, outer bool) string {
	value := goType(column.DBType)
	if sumType, avgType, numeric := numericAggregateTypes(column.DBType); numeric {
		if column.Nullable || outer {
			return fmt.Sprintf("tiqq.NumericColumn[%s, sql.Null[%s], %s, %s, %s]", scope, value, value, sumType, avgType)
		}
		return fmt.Sprintf("tiqq.NumericColumn[%s, %s, %s, %s, %s]", scope, value, value, sumType, avgType)
	}
	if column.Nullable || outer {
		return fmt.Sprintf("tiqq.Column[%s, sql.Null[%s], %s]", scope, value, value)
	}
	return fmt.Sprintf("tiqq.Column[%s, %s, %s]", scope, value, value)
}

func numericAggregateTypes(databaseType string) (string, string, bool) {
	switch databaseType {
	case "int2", "smallint", "smallserial", "int4", "integer", "serial":
		return "int64", "tiqq.Decimal", true
	case "int8", "bigint", "bigserial", "numeric", "decimal":
		return "tiqq.Decimal", "tiqq.Decimal", true
	case "float4", "real":
		return "float32", "float64", true
	case "float8", "double precision":
		return "float64", "float64", true
	default:
		return "", "", false
	}
}

func goType(databaseType string) string {
	switch databaseType {
	case "int8", "bigint", "bigserial":
		return "int64"
	case "int4", "integer", "serial":
		return "int32"
	case "int2", "smallint", "smallserial":
		return "int16"
	case "bool", "boolean":
		return "bool"
	case "bytea":
		return "[]byte"
	case "float4", "real":
		return "float32"
	case "float8", "double precision":
		return "float64"
	case "numeric", "decimal":
		return "tiqq.Decimal"
	default:
		return "string"
	}
}

func singular(name string) string {
	if strings.HasSuffix(name, "sses") {
		return strings.TrimSuffix(name, "es")
	}
	if strings.HasSuffix(name, "ies") {
		return strings.TrimSuffix(name, "ies") + "y"
	}
	if strings.HasSuffix(name, "s") {
		return strings.TrimSuffix(name, "s")
	}
	return name
}

func exported(name string) string {
	parts := strings.FieldsFunc(name, func(character rune) bool { return character == '_' || character == '-' })
	for index, part := range parts {
		upper := strings.ToUpper(part)
		if upper == "ID" {
			parts[index] = upper
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}
