// Package codegen emits the typed Go API from schema IR.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/eji/tiqq/schema"
)

type Config struct {
	Package string
}

// Generate emits table definitions and unambiguous FK-based InnerJoin and
// LeftJoin types. The output is gofmt formatted and deterministic.
func Generate(database schema.Schema, config Config) ([]byte, error) {
	if config.Package == "" {
		return nil, fmt.Errorf("codegen: package name is required")
	}
	tables := append([]schema.Table(nil), database.Tables...)
	sort.Slice(tables, func(i, j int) bool { return tables[i].Name < tables[j].Name })
	relations, err := relationsByParent(tables)
	if err != nil {
		return nil, err
	}

	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by tiqq; DO NOT EDIT.\npackage %s\n\n", config.Package)
	output.WriteString("import (\n")
	if usesNullable(tables) || len(relations) > 0 {
		output.WriteString("\t\"database/sql\"\n\n")
	}
	output.WriteString("\t\"github.com/eji/tiqq\"\n)\n\n")
	for _, table := range tables {
		writeTable(&output, table)
	}
	for _, relation := range relations {
		if relation.parent.Name == relation.child.Name {
			writeSelfRelation(&output, relation.parent)
		} else {
			writeRelation(&output, relation.parent, relation.child)
		}
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: format generated source: %w", err)
	}
	return formatted, nil
}

func writeSelfRelation(output *bytes.Buffer, table schema.Table) {
	tableName := exported(singular(table.Name))
	aliasScope := tableName + "AliasScope"
	joinScope := tableName + "SelfJoinScope"
	fmt.Fprintf(output, "type %s struct{}\ntype %s struct{}\n\n", aliasScope, joinScope)
	fmt.Fprintf(output, "type %sAliasTableDef struct {\n\talias string\n", tableName)
	for _, column := range table.Columns {
		fmt.Fprintf(output, "\t%s %s\n", exported(column.Name), columnType(aliasScope, column, false))
	}
	output.WriteString("}\n\n")
	fmt.Fprintf(output, "func (table %sTableDef) As(alias string) %sAliasTableDef {\n", tableName, tableName)
	fmt.Fprintf(output, "return %sAliasTableDef{alias: alias,\n", tableName)
	for _, column := range table.Columns {
		fmt.Fprintf(output, "\t%s: tiqq.AliasColumn[%sScope, %s](table.%s, alias),\n", exported(column.Name), tableName, aliasScope, exported(column.Name))
	}
	output.WriteString("}\n}\n\n")
	writeView(output, "selfJoined"+tableName+"View", joinScope, table, false)
	writeView(output, "nullableSelfJoined"+tableName+"View", joinScope, table, true)
	fmt.Fprintf(output, "type %sSelfInnerJoin struct { left selfJoined%sView; right selfJoined%sView; source tiqq.Source }\n", tableName, tableName, tableName)
	fmt.Fprintf(output, "type %sSelfLeftJoin struct { left selfJoined%sView; right nullableSelfJoined%sView; source tiqq.Source }\n\n", tableName, tableName, tableName)
	writeSelfJoinConstructor(output, tableName, aliasScope, joinScope, table, "Inner", false)
	writeSelfJoinConstructor(output, tableName, aliasScope, joinScope, table, "Left", true)
	writeJoinMethods(output, tableName+"SelfInnerJoin", "selfJoined"+tableName+"View", "selfJoined"+tableName+"View", joinScope)
	writeJoinMethods(output, tableName+"SelfLeftJoin", "selfJoined"+tableName+"View", "nullableSelfJoined"+tableName+"View", joinScope)
}

func writeSelfJoinConstructor(output *bytes.Buffer, tableName, aliasScope, joinScope string, table schema.Table, kind string, outer bool) {
	joinType := tableName + "Self" + kind + "Join"
	fmt.Fprintf(output, "func (left %sAliasTableDef) %sJoin(right %sAliasTableDef, on tiqq.JoinCondition) %s {\n", tableName, kind, tableName, joinType)
	output.WriteString("tiqq.RequireDistinctAliases(left.alias, right.alias)\n")
	fmt.Fprintf(output, "return %s{left: selfJoined%sView{\n", joinType, tableName)
	writeRebindings(output, "left", aliasScope, joinScope, table, false)
	rightView := "selfJoined" + tableName + "View"
	if outer {
		rightView = "nullableSelfJoined" + tableName + "View"
	}
	fmt.Fprintf(output, "}, right: %s{\n", rightView)
	writeRebindings(output, "right", aliasScope, joinScope, table, outer)
	fmt.Fprintf(output, "}, source: tiqq.NewAliased%sJoinSource(%q, left.alias, %q, right.alias, on)}\n}\n\n", kind, table.Name, table.Name)
}

func usesNullable(tables []schema.Table) bool {
	for _, table := range tables {
		for _, column := range table.Columns {
			if column.Nullable {
				return true
			}
		}
	}
	return false
}

type relation struct{ parent, child schema.Table }

func relationsByParent(tables []schema.Table) ([]relation, error) {
	byName := make(map[string]schema.Table, len(tables))
	for _, table := range tables {
		byName[table.Name] = table
	}
	counts := map[string]int{}
	var result []relation
	for _, child := range tables {
		for _, foreignKey := range child.ForeignKeys {
			parent, found := byName[foreignKey.ReferencedTable]
			if !found {
				return nil, fmt.Errorf("codegen: foreign key %s references unknown table %s", foreignKey.Name, foreignKey.ReferencedTable)
			}
			counts[parent.Name]++
			result = append(result, relation{parent: parent, child: child})
		}
	}
	for table, count := range counts {
		if count > 1 {
			return nil, fmt.Errorf("codegen: table %s has multiple join relations; explicit relation API is required", table)
		}
	}
	return result, nil
}

func writeTable(output *bytes.Buffer, table schema.Table) {
	typeName := exported(singular(table.Name))
	fmt.Fprintf(output, "type %sScope struct{}\n\ntype %sTableDef struct {\n", typeName, typeName)
	for _, column := range table.Columns {
		fmt.Fprintf(output, "\t%s %s\n", exported(column.Name), columnType(typeName+"Scope", column, false))
	}
	output.WriteString("}\n\n")
	fmt.Fprintf(output, "var %sTable = %sTableDef{\n", typeName, typeName)
	for _, column := range table.Columns {
		constructor := "RequiredColumn"
		if column.Nullable {
			constructor = "NullableColumn"
		}
		fmt.Fprintf(output, "\t%s: tiqq.%s[%sScope, %s](%q, %q),\n", exported(column.Name), constructor, typeName, goType(column.DBType), table.Name, column.Name)
	}
	output.WriteString("}\n\n")
}

func writeRelation(output *bytes.Buffer, parent, child schema.Table) {
	parentName, childName := exported(singular(parent.Name)), exported(singular(child.Name))
	scope := parentName + childName + "Scope"
	fmt.Fprintf(output, "type %s struct{}\n\n", scope)
	writeView(output, "joined"+parentName+"View", scope, parent, false)
	writeView(output, "joined"+childName+"View", scope, child, false)
	writeView(output, "nullable"+childName+"View", scope, child, true)
	fmt.Fprintf(output, "type %s%sInnerJoin struct { left joined%sView; right joined%sView; source tiqq.Source }\n", parentName, childName, parentName, childName)
	fmt.Fprintf(output, "type %s%sLeftJoin struct { left joined%sView; right nullable%sView; source tiqq.Source }\n\n", parentName, childName, parentName, childName)
	writeJoinConstructor(output, parentName, childName, scope, parent, child, "Inner", false)
	writeJoinConstructor(output, parentName, childName, scope, parent, child, "Left", true)
	writeJoinMethods(output, parentName+childName+"InnerJoin", "joined"+parentName+"View", "joined"+childName+"View", scope)
	writeJoinMethods(output, parentName+childName+"LeftJoin", "joined"+parentName+"View", "nullable"+childName+"View", scope)
}

func writeView(output *bytes.Buffer, name, scope string, table schema.Table, outer bool) {
	fmt.Fprintf(output, "type %s struct {\n", name)
	for _, column := range table.Columns {
		fmt.Fprintf(output, "\t%s %s\n", exported(column.Name), columnType(scope, column, outer))
	}
	output.WriteString("}\n\n")
}

func writeJoinConstructor(output *bytes.Buffer, parentName, childName, scope string, parent, child schema.Table, kind string, outer bool) {
	joinType := parentName + childName + kind + "Join"
	fmt.Fprintf(output, "func (table %sTableDef) %sJoin(right %sTableDef, on tiqq.JoinCondition) %s {\n", parentName, kind, childName, joinType)
	fmt.Fprintf(output, "return %s{left: joined%sView{\n", joinType, parentName)
	writeRebindings(output, "table", parentName+"Scope", scope, parent, false)
	rightView := "joined" + childName + "View"
	if outer {
		rightView = "nullable" + childName + "View"
	}
	fmt.Fprintf(output, "}, right: %s{\n", rightView)
	writeRebindings(output, "right", childName+"Scope", scope, child, outer)
	fmt.Fprintf(output, "}, source: tiqq.New%sJoinSource(%q, %q, on)}\n}\n\n", kind, parent.Name, child.Name)
}

func writeRebindings(output *bytes.Buffer, variable, from, to string, table schema.Table, outer bool) {
	for _, column := range table.Columns {
		function := "RebindRequired"
		if column.Nullable {
			function = "RebindExistingNullable"
		}
		if outer && !column.Nullable {
			function = "RebindNullable"
		}
		fmt.Fprintf(output, "\t%s: tiqq.%s[%s, %s](%s.%s),\n", exported(column.Name), function, from, to, variable, exported(column.Name))
	}
}

func writeJoinMethods(output *bytes.Buffer, joinType, leftView, rightView, scope string) {
	fmt.Fprintf(output, "func (join %s) Left() %s { return join.left }\n", joinType, leftView)
	fmt.Fprintf(output, "func (join %s) Right() %s { return join.right }\n", joinType, rightView)
	fmt.Fprintf(output, "func (join %s) Where(predicates ...tiqq.Predicate[%s]) tiqq.Query[%s] { return tiqq.NewQuery[%s](join.source).Where(predicates...) }\n", joinType, scope, scope, scope)
	fmt.Fprintf(output, "func (join %s) Select(columns ...tiqq.Selection[%s]) tiqq.Query[%s] { return tiqq.NewQuery[%s](join.source).Select(columns...) }\n\n", joinType, scope, scope, scope)
}

func columnType(scope string, column schema.Column, outer bool) string {
	value := goType(column.DBType)
	if column.Nullable || outer {
		return fmt.Sprintf("tiqq.Column[%s, sql.Null[%s], %s]", scope, value, value)
	}
	return fmt.Sprintf("tiqq.Column[%s, %s, %s]", scope, value, value)
}

func goType(databaseType string) string {
	switch databaseType {
	case "int8", "bigint", "bigserial":
		return "int64"
	case "int4", "integer", "serial":
		return "int32"
	case "int2", "smallint", "smallserial":
		return "int16"
	case "bool", "boolean":
		return "bool"
	case "bytea":
		return "[]byte"
	case "float4", "real":
		return "float32"
	case "float8", "double precision":
		return "float64"
	case "numeric", "decimal":
		return "tiqq.Decimal"
	default:
		return "string"
	}
}

func singular(name string) string {
	if strings.HasSuffix(name, "sses") {
		return strings.TrimSuffix(name, "es")
	}
	if strings.HasSuffix(name, "ies") {
		return strings.TrimSuffix(name, "ies") + "y"
	}
	if strings.HasSuffix(name, "s") {
		return strings.TrimSuffix(name, "s")
	}
	return name
}

func exported(name string) string {
	parts := strings.FieldsFunc(name, func(character rune) bool { return character == '_' || character == '-' })
	for index, part := range parts {
		upper := strings.ToUpper(part)
		if upper == "ID" {
			parts[index] = upper
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}
	return strings.Join(parts, "")
}
