// Code generated by tiqq; DO NOT EDIT.
package schema

import (
	"database/sql"

	"github.com/eji/tiqq"
)

type AddressScope struct{}

type AddressTableDef struct {
	ref       tiqq.TableRef
	ID        tiqq.Column[AddressScope, int64, int64]
	UserID    tiqq.Column[AddressScope, int64, int64]
	CompanyID tiqq.Column[AddressScope, int64, int64]
	Address   tiqq.Column[AddressScope, string, string]
}

type NullableAddressTableDef struct {
	ID        tiqq.Column[AddressScope, sql.Null[int64], int64]
	UserID    tiqq.Column[AddressScope, sql.Null[int64], int64]
	CompanyID tiqq.Column[AddressScope, sql.Null[int64], int64]
	Address   tiqq.Column[AddressScope, sql.Null[string], string]
}

var AddressTable = AddressTableDef{
	ref:       tiqq.NewTableRef("addresses"),
	ID:        tiqq.RequiredColumn[AddressScope, int64]("addresses", "id"),
	UserID:    tiqq.RequiredColumn[AddressScope, int64]("addresses", "user_id"),
	CompanyID: tiqq.RequiredColumn[AddressScope, int64]("addresses", "company_id"),
	Address:   tiqq.RequiredColumn[AddressScope, string]("addresses", "address"),
}

func (table AddressTableDef) TiqqTableInfo() tiqq.TableInfo[AddressTableDef, NullableAddressTableDef] {
	return tiqq.NewTableInfo(table.ref, table, NullableAddressTableDef{
		ID:        tiqq.RebindNullable[AddressScope, AddressScope](table.ID),
		UserID:    tiqq.RebindNullable[AddressScope, AddressScope](table.UserID),
		CompanyID: tiqq.RebindNullable[AddressScope, AddressScope](table.CompanyID),
		Address:   tiqq.RebindNullable[AddressScope, AddressScope](table.Address),
	}, []tiqq.ForeignKey{{Columns: []string{"user_id"}, ReferencedTable: "users", ReferencedColumns: []string{"id"}}, {Columns: []string{"company_id"}, ReferencedTable: "companies", ReferencedColumns: []string{"id"}}})
}

func (table AddressTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[AddressTableDef] {
	return tiqq.TableJoinSource(table.TiqqTableInfo())
}
func (table AddressTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[AddressTableDef, NC] {
	return tiqq.LeftJoin(table, right)
}
func (table AddressTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[AddressTableDef, C] {
	return tiqq.InnerJoin(table, right)
}
func (table AddressTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query {
	return tiqq.NewTableQuery(table).Where(predicates...)
}
func (table AddressTableDef) Select(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).Select(columns...)
}
func (table AddressTableDef) Update() tiqq.UpdateQuery[AddressScope] {
	return tiqq.NewUpdate[AddressScope](table)
}
func (table AddressTableDef) Insert() tiqq.InsertQuery[AddressScope] {
	return tiqq.NewInsert[AddressScope](table.ref, []string{"id", "user_id", "company_id", "address"}, []string{"id", "user_id", "company_id", "address"})
}
func (table AddressTableDef) As(alias string) AddressTableDef {
	table.ref = table.ref.As(alias)
	table.ID = tiqq.AliasColumn[AddressScope, AddressScope](table.ID, alias)
	table.UserID = tiqq.AliasColumn[AddressScope, AddressScope](table.UserID, alias)
	table.CompanyID = tiqq.AliasColumn[AddressScope, AddressScope](table.CompanyID, alias)
	table.Address = tiqq.AliasColumn[AddressScope, AddressScope](table.Address, alias)
	return table
}

type AuditLogScope struct{}

type AuditLogTableDef struct {
	ref     tiqq.TableRef
	ID      tiqq.Column[AuditLogScope, int64, int64]
	ActorID tiqq.Column[AuditLogScope, int64, int64]
	Active  tiqq.Column[AuditLogScope, bool, bool]
	Message tiqq.Column[AuditLogScope, string, string]
}

type NullableAuditLogTableDef struct {
	ID      tiqq.Column[AuditLogScope, sql.Null[int64], int64]
	ActorID tiqq.Column[AuditLogScope, sql.Null[int64], int64]
	Active  tiqq.Column[AuditLogScope, sql.Null[bool], bool]
	Message tiqq.Column[AuditLogScope, sql.Null[string], string]
}

var AuditLogTable = AuditLogTableDef{
	ref:     tiqq.NewTableRef("audit_logs"),
	ID:      tiqq.RequiredColumn[AuditLogScope, int64]("audit_logs", "id"),
	ActorID: tiqq.RequiredColumn[AuditLogScope, int64]("audit_logs", "actor_id"),
	Active:  tiqq.RequiredColumn[AuditLogScope, bool]("audit_logs", "active"),
	Message: tiqq.RequiredColumn[AuditLogScope, string]("audit_logs", "message"),
}

func (table AuditLogTableDef) TiqqTableInfo() tiqq.TableInfo[AuditLogTableDef, NullableAuditLogTableDef] {
	return tiqq.NewTableInfo(table.ref, table, NullableAuditLogTableDef{
		ID:      tiqq.RebindNullable[AuditLogScope, AuditLogScope](table.ID),
		ActorID: tiqq.RebindNullable[AuditLogScope, AuditLogScope](table.ActorID),
		Active:  tiqq.RebindNullable[AuditLogScope, AuditLogScope](table.Active),
		Message: tiqq.RebindNullable[AuditLogScope, AuditLogScope](table.Message),
	}, []tiqq.ForeignKey{})
}

func (table AuditLogTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[AuditLogTableDef] {
	return tiqq.TableJoinSource(table.TiqqTableInfo())
}
func (table AuditLogTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[AuditLogTableDef, NC] {
	return tiqq.LeftJoin(table, right)
}
func (table AuditLogTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[AuditLogTableDef, C] {
	return tiqq.InnerJoin(table, right)
}
func (table AuditLogTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query {
	return tiqq.NewTableQuery(table).Where(predicates...)
}
func (table AuditLogTableDef) Select(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).Select(columns...)
}
func (table AuditLogTableDef) Update() tiqq.UpdateQuery[AuditLogScope] {
	return tiqq.NewUpdate[AuditLogScope](table)
}
func (table AuditLogTableDef) Insert() tiqq.InsertQuery[AuditLogScope] {
	return tiqq.NewInsert[AuditLogScope](table.ref, []string{"id", "actor_id", "active", "message"}, []string{"id", "actor_id", "active", "message"})
}
func (table AuditLogTableDef) As(alias string) AuditLogTableDef {
	table.ref = table.ref.As(alias)
	table.ID = tiqq.AliasColumn[AuditLogScope, AuditLogScope](table.ID, alias)
	table.ActorID = tiqq.AliasColumn[AuditLogScope, AuditLogScope](table.ActorID, alias)
	table.Active = tiqq.AliasColumn[AuditLogScope, AuditLogScope](table.Active, alias)
	table.Message = tiqq.AliasColumn[AuditLogScope, AuditLogScope](table.Message, alias)
	return table
}

type CompanyScope struct{}

type CompanyTableDef struct {
	ref  tiqq.TableRef
	ID   tiqq.Column[CompanyScope, int64, int64]
	Name tiqq.Column[CompanyScope, string, string]
}

type NullableCompanyTableDef struct {
	ID   tiqq.Column[CompanyScope, sql.Null[int64], int64]
	Name tiqq.Column[CompanyScope, sql.Null[string], string]
}

var CompanyTable = CompanyTableDef{
	ref:  tiqq.NewTableRef("companies"),
	ID:   tiqq.RequiredColumn[CompanyScope, int64]("companies", "id"),
	Name: tiqq.RequiredColumn[CompanyScope, string]("companies", "name"),
}

func (table CompanyTableDef) TiqqTableInfo() tiqq.TableInfo[CompanyTableDef, NullableCompanyTableDef] {
	return tiqq.NewTableInfo(table.ref, table, NullableCompanyTableDef{
		ID:   tiqq.RebindNullable[CompanyScope, CompanyScope](table.ID),
		Name: tiqq.RebindNullable[CompanyScope, CompanyScope](table.Name),
	}, []tiqq.ForeignKey{})
}

func (table CompanyTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[CompanyTableDef] {
	return tiqq.TableJoinSource(table.TiqqTableInfo())
}
func (table CompanyTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[CompanyTableDef, NC] {
	return tiqq.LeftJoin(table, right)
}
func (table CompanyTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[CompanyTableDef, C] {
	return tiqq.InnerJoin(table, right)
}
func (table CompanyTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query {
	return tiqq.NewTableQuery(table).Where(predicates...)
}
func (table CompanyTableDef) Select(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).Select(columns...)
}
func (table CompanyTableDef) Update() tiqq.UpdateQuery[CompanyScope] {
	return tiqq.NewUpdate[CompanyScope](table)
}
func (table CompanyTableDef) Insert() tiqq.InsertQuery[CompanyScope] {
	return tiqq.NewInsert[CompanyScope](table.ref, []string{"id", "name"}, []string{"id", "name"})
}
func (table CompanyTableDef) As(alias string) CompanyTableDef {
	table.ref = table.ref.As(alias)
	table.ID = tiqq.AliasColumn[CompanyScope, CompanyScope](table.ID, alias)
	table.Name = tiqq.AliasColumn[CompanyScope, CompanyScope](table.Name, alias)
	return table
}

type UserScope struct{}

type UserTableDef struct {
	ref       tiqq.TableRef
	ID        tiqq.Column[UserScope, int64, int64]
	Name      tiqq.Column[UserScope, string, string]
	ManagerID tiqq.Column[UserScope, sql.Null[int64], int64]
}

type NullableUserTableDef struct {
	ID        tiqq.Column[UserScope, sql.Null[int64], int64]
	Name      tiqq.Column[UserScope, sql.Null[string], string]
	ManagerID tiqq.Column[UserScope, sql.Null[int64], int64]
}

var UserTable = UserTableDef{
	ref:       tiqq.NewTableRef("users"),
	ID:        tiqq.RequiredColumn[UserScope, int64]("users", "id"),
	Name:      tiqq.RequiredColumn[UserScope, string]("users", "name"),
	ManagerID: tiqq.NullableColumn[UserScope, int64]("users", "manager_id"),
}

func (table UserTableDef) TiqqTableInfo() tiqq.TableInfo[UserTableDef, NullableUserTableDef] {
	return tiqq.NewTableInfo(table.ref, table, NullableUserTableDef{
		ID:        tiqq.RebindNullable[UserScope, UserScope](table.ID),
		Name:      tiqq.RebindNullable[UserScope, UserScope](table.Name),
		ManagerID: tiqq.RebindExistingNullable[UserScope, UserScope](table.ManagerID),
	}, []tiqq.ForeignKey{{Columns: []string{"manager_id"}, ReferencedTable: "users", ReferencedColumns: []string{"id"}}})
}

func (table UserTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[UserTableDef] {
	return tiqq.TableJoinSource(table.TiqqTableInfo())
}
func (table UserTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[UserTableDef, NC] {
	return tiqq.LeftJoin(table, right)
}
func (table UserTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[UserTableDef, C] {
	return tiqq.InnerJoin(table, right)
}
func (table UserTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query {
	return tiqq.NewTableQuery(table).Where(predicates...)
}
func (table UserTableDef) Select(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).Select(columns...)
}
func (table UserTableDef) Update() tiqq.UpdateQuery[UserScope] {
	return tiqq.NewUpdate[UserScope](table)
}
func (table UserTableDef) Insert() tiqq.InsertQuery[UserScope] {
	return tiqq.NewInsert[UserScope](table.ref, []string{"id", "name", "manager_id"}, []string{"id", "name"})
}
func (table UserTableDef) As(alias string) UserTableDef {
	table.ref = table.ref.As(alias)
	table.ID = tiqq.AliasColumn[UserScope, UserScope](table.ID, alias)
	table.Name = tiqq.AliasColumn[UserScope, UserScope](table.Name, alias)
	table.ManagerID = tiqq.AliasColumn[UserScope, UserScope](table.ManagerID, alias)
	return table
}
