// Code generated by tiqq; DO NOT EDIT.
package schema

import (
	"database/sql"

	"github.com/eji/tiqq"
	"github.com/eji/tiqq/postgres"
)

var tiqqSchema = tiqq.NewSchemaInfo(tiqq.PostgreSQL)

type AddressScope struct{}

type AddressTableDef struct {
	ref       tiqq.TableRef
	ID        tiqq.NumericColumn[AddressScope, int64, int64, tiqq.Decimal, tiqq.Decimal]
	UserID    tiqq.NumericColumn[AddressScope, int64, int64, tiqq.Decimal, tiqq.Decimal]
	CompanyID tiqq.NumericColumn[AddressScope, int64, int64, tiqq.Decimal, tiqq.Decimal]
	Address   tiqq.Column[AddressScope, string, string]
}

type NullableAddressTableDef struct {
	ID        tiqq.NumericColumn[AddressScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
	UserID    tiqq.NumericColumn[AddressScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
	CompanyID tiqq.NumericColumn[AddressScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
	Address   tiqq.Column[AddressScope, sql.Null[string], string]
}

var AddressTable = AddressTableDef{
	ref:       tiqqSchema.Table("addresses"),
	ID:        tiqq.RequiredNumericColumn[AddressScope, int64, tiqq.Decimal, tiqq.Decimal]("addresses", "id"),
	UserID:    tiqq.RequiredNumericColumn[AddressScope, int64, tiqq.Decimal, tiqq.Decimal]("addresses", "user_id"),
	CompanyID: tiqq.RequiredNumericColumn[AddressScope, int64, tiqq.Decimal, tiqq.Decimal]("addresses", "company_id"),
	Address:   tiqq.RequiredColumn[AddressScope, string]("addresses", "address"),
}

func (table AddressTableDef) TiqqTableInfo() tiqq.TableInfo[AddressTableDef, NullableAddressTableDef] {
	return tiqq.NewTableInfo(table.ref, table, NullableAddressTableDef{
		ID:        tiqq.RebindNullableNumeric[AddressScope, AddressScope](table.ID),
		UserID:    tiqq.RebindNullableNumeric[AddressScope, AddressScope](table.UserID),
		CompanyID: tiqq.RebindNullableNumeric[AddressScope, AddressScope](table.CompanyID),
		Address:   tiqq.RebindNullable[AddressScope, AddressScope](table.Address),
	}, []tiqq.ForeignKey{{Columns: []string{"user_id"}, ReferencedTable: "users", ReferencedColumns: []string{"id"}}, {Columns: []string{"company_id"}, ReferencedTable: "companies", ReferencedColumns: []string{"id"}}})
}

func (table AddressTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[AddressTableDef] {
	return tiqq.TableJoinSource(table.TiqqTableInfo())
}
func (table AddressTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[AddressTableDef, NC] {
	return tiqq.LeftJoin(table, right)
}
func (table AddressTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[AddressTableDef, C] {
	return tiqq.InnerJoin(table, right)
}
func (table AddressTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query {
	return tiqq.NewTableQuery(table).Where(predicates...)
}
func (table AddressTableDef) Select(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).Select(columns...)
}
func (table AddressTableDef) GroupBy(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).GroupBy(columns...)
}
func (table AddressTableDef) Update() tiqq.UpdateQuery[AddressScope] {
	return tiqq.NewUpdate[AddressScope](table)
}
func (table AddressTableDef) Delete() tiqq.DeleteQuery[AddressScope] {
	return tiqq.NewDelete[AddressScope](table)
}
func (table AddressTableDef) Insert() postgres.InsertQuery[AddressScope] {
	return postgres.NewInsert(tiqq.NewInsert[AddressScope, tiqq.PostgreSQLMarker](table.ref, []string{"id", "user_id", "company_id", "address"}, []string{"id", "user_id", "company_id", "address"}, [][]string{{"id"}}))
}
func (table AddressTableDef) As(alias string) AddressTableDef {
	table.ref = table.ref.As(alias)
	table.ID = tiqq.AliasNumericColumn[AddressScope, AddressScope](table.ID, alias)
	table.UserID = tiqq.AliasNumericColumn[AddressScope, AddressScope](table.UserID, alias)
	table.CompanyID = tiqq.AliasNumericColumn[AddressScope, AddressScope](table.CompanyID, alias)
	table.Address = tiqq.AliasColumn[AddressScope, AddressScope](table.Address, alias)
	return table
}

type AuditLogScope struct{}

type AuditLogTableDef struct {
	ref     tiqq.TableRef
	ID      tiqq.NumericColumn[AuditLogScope, int64, int64, tiqq.Decimal, tiqq.Decimal]
	ActorID tiqq.NumericColumn[AuditLogScope, int64, int64, tiqq.Decimal, tiqq.Decimal]
	Active  tiqq.Column[AuditLogScope, bool, bool]
	Message tiqq.Column[AuditLogScope, string, string]
}

type NullableAuditLogTableDef struct {
	ID      tiqq.NumericColumn[AuditLogScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
	ActorID tiqq.NumericColumn[AuditLogScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
	Active  tiqq.Column[AuditLogScope, sql.Null[bool], bool]
	Message tiqq.Column[AuditLogScope, sql.Null[string], string]
}

var AuditLogTable = AuditLogTableDef{
	ref:     tiqqSchema.Table("audit_logs"),
	ID:      tiqq.RequiredNumericColumn[AuditLogScope, int64, tiqq.Decimal, tiqq.Decimal]("audit_logs", "id"),
	ActorID: tiqq.RequiredNumericColumn[AuditLogScope, int64, tiqq.Decimal, tiqq.Decimal]("audit_logs", "actor_id"),
	Active:  tiqq.RequiredColumn[AuditLogScope, bool]("audit_logs", "active"),
	Message: tiqq.RequiredColumn[AuditLogScope, string]("audit_logs", "message"),
}

func (table AuditLogTableDef) TiqqTableInfo() tiqq.TableInfo[AuditLogTableDef, NullableAuditLogTableDef] {
	return tiqq.NewTableInfo(table.ref, table, NullableAuditLogTableDef{
		ID:      tiqq.RebindNullableNumeric[AuditLogScope, AuditLogScope](table.ID),
		ActorID: tiqq.RebindNullableNumeric[AuditLogScope, AuditLogScope](table.ActorID),
		Active:  tiqq.RebindNullable[AuditLogScope, AuditLogScope](table.Active),
		Message: tiqq.RebindNullable[AuditLogScope, AuditLogScope](table.Message),
	}, []tiqq.ForeignKey{})
}

func (table AuditLogTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[AuditLogTableDef] {
	return tiqq.TableJoinSource(table.TiqqTableInfo())
}
func (table AuditLogTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[AuditLogTableDef, NC] {
	return tiqq.LeftJoin(table, right)
}
func (table AuditLogTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[AuditLogTableDef, C] {
	return tiqq.InnerJoin(table, right)
}
func (table AuditLogTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query {
	return tiqq.NewTableQuery(table).Where(predicates...)
}
func (table AuditLogTableDef) Select(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).Select(columns...)
}
func (table AuditLogTableDef) GroupBy(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).GroupBy(columns...)
}
func (table AuditLogTableDef) Update() tiqq.UpdateQuery[AuditLogScope] {
	return tiqq.NewUpdate[AuditLogScope](table)
}
func (table AuditLogTableDef) Delete() tiqq.DeleteQuery[AuditLogScope] {
	return tiqq.NewDelete[AuditLogScope](table)
}
func (table AuditLogTableDef) Insert() postgres.InsertQuery[AuditLogScope] {
	return postgres.NewInsert(tiqq.NewInsert[AuditLogScope, tiqq.PostgreSQLMarker](table.ref, []string{"id", "actor_id", "active", "message"}, []string{"id", "actor_id", "active", "message"}, [][]string{{"id"}}))
}
func (table AuditLogTableDef) As(alias string) AuditLogTableDef {
	table.ref = table.ref.As(alias)
	table.ID = tiqq.AliasNumericColumn[AuditLogScope, AuditLogScope](table.ID, alias)
	table.ActorID = tiqq.AliasNumericColumn[AuditLogScope, AuditLogScope](table.ActorID, alias)
	table.Active = tiqq.AliasColumn[AuditLogScope, AuditLogScope](table.Active, alias)
	table.Message = tiqq.AliasColumn[AuditLogScope, AuditLogScope](table.Message, alias)
	return table
}

type CompanyScope struct{}

type CompanyTableDef struct {
	ref  tiqq.TableRef
	ID   tiqq.NumericColumn[CompanyScope, int64, int64, tiqq.Decimal, tiqq.Decimal]
	Name tiqq.Column[CompanyScope, string, string]
}

type NullableCompanyTableDef struct {
	ID   tiqq.NumericColumn[CompanyScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
	Name tiqq.Column[CompanyScope, sql.Null[string], string]
}

var CompanyTable = CompanyTableDef{
	ref:  tiqqSchema.Table("companies"),
	ID:   tiqq.RequiredNumericColumn[CompanyScope, int64, tiqq.Decimal, tiqq.Decimal]("companies", "id"),
	Name: tiqq.RequiredColumn[CompanyScope, string]("companies", "name"),
}

func (table CompanyTableDef) TiqqTableInfo() tiqq.TableInfo[CompanyTableDef, NullableCompanyTableDef] {
	return tiqq.NewTableInfo(table.ref, table, NullableCompanyTableDef{
		ID:   tiqq.RebindNullableNumeric[CompanyScope, CompanyScope](table.ID),
		Name: tiqq.RebindNullable[CompanyScope, CompanyScope](table.Name),
	}, []tiqq.ForeignKey{})
}

func (table CompanyTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[CompanyTableDef] {
	return tiqq.TableJoinSource(table.TiqqTableInfo())
}
func (table CompanyTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[CompanyTableDef, NC] {
	return tiqq.LeftJoin(table, right)
}
func (table CompanyTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[CompanyTableDef, C] {
	return tiqq.InnerJoin(table, right)
}
func (table CompanyTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query {
	return tiqq.NewTableQuery(table).Where(predicates...)
}
func (table CompanyTableDef) Select(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).Select(columns...)
}
func (table CompanyTableDef) GroupBy(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).GroupBy(columns...)
}
func (table CompanyTableDef) Update() tiqq.UpdateQuery[CompanyScope] {
	return tiqq.NewUpdate[CompanyScope](table)
}
func (table CompanyTableDef) Delete() tiqq.DeleteQuery[CompanyScope] {
	return tiqq.NewDelete[CompanyScope](table)
}
func (table CompanyTableDef) Insert() postgres.InsertQuery[CompanyScope] {
	return postgres.NewInsert(tiqq.NewInsert[CompanyScope, tiqq.PostgreSQLMarker](table.ref, []string{"id", "name"}, []string{"id", "name"}, [][]string{{"id"}}))
}
func (table CompanyTableDef) As(alias string) CompanyTableDef {
	table.ref = table.ref.As(alias)
	table.ID = tiqq.AliasNumericColumn[CompanyScope, CompanyScope](table.ID, alias)
	table.Name = tiqq.AliasColumn[CompanyScope, CompanyScope](table.Name, alias)
	return table
}

type UserScope struct{}

type UserTableDef struct {
	ref       tiqq.TableRef
	ID        tiqq.NumericColumn[UserScope, int64, int64, tiqq.Decimal, tiqq.Decimal]
	Name      tiqq.Column[UserScope, string, string]
	ManagerID tiqq.NumericColumn[UserScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
}

type NullableUserTableDef struct {
	ID        tiqq.NumericColumn[UserScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
	Name      tiqq.Column[UserScope, sql.Null[string], string]
	ManagerID tiqq.NumericColumn[UserScope, sql.Null[int64], int64, tiqq.Decimal, tiqq.Decimal]
}

var UserTable = UserTableDef{
	ref:       tiqqSchema.Table("users"),
	ID:        tiqq.RequiredNumericColumn[UserScope, int64, tiqq.Decimal, tiqq.Decimal]("users", "id"),
	Name:      tiqq.RequiredColumn[UserScope, string]("users", "name"),
	ManagerID: tiqq.NullableNumericColumn[UserScope, int64, tiqq.Decimal, tiqq.Decimal]("users", "manager_id"),
}

func (table UserTableDef) TiqqTableInfo() tiqq.TableInfo[UserTableDef, NullableUserTableDef] {
	return tiqq.NewTableInfo(table.ref, table, NullableUserTableDef{
		ID:        tiqq.RebindNullableNumeric[UserScope, UserScope](table.ID),
		Name:      tiqq.RebindNullable[UserScope, UserScope](table.Name),
		ManagerID: tiqq.RebindExistingNullableNumeric[UserScope, UserScope](table.ManagerID),
	}, []tiqq.ForeignKey{{Columns: []string{"manager_id"}, ReferencedTable: "users", ReferencedColumns: []string{"id"}}})
}

func (table UserTableDef) TiqqJoinSource() tiqq.JoinSourceInfo[UserTableDef] {
	return tiqq.TableJoinSource(table.TiqqTableInfo())
}
func (table UserTableDef) LeftJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[UserTableDef, NC] {
	return tiqq.LeftJoin(table, right)
}
func (table UserTableDef) InnerJoin[C, NC any, R tiqq.TableLike[C, NC]](right R) tiqq.Joined[UserTableDef, C] {
	return tiqq.InnerJoin(table, right)
}
func (table UserTableDef) Where(predicates ...tiqq.Predicate) tiqq.Query {
	return tiqq.NewTableQuery(table).Where(predicates...)
}
func (table UserTableDef) Select(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).Select(columns...)
}
func (table UserTableDef) GroupBy(columns ...tiqq.Selection) tiqq.Query {
	return tiqq.NewTableQuery(table).GroupBy(columns...)
}
func (table UserTableDef) Update() tiqq.UpdateQuery[UserScope] {
	return tiqq.NewUpdate[UserScope](table)
}
func (table UserTableDef) Delete() tiqq.DeleteQuery[UserScope] {
	return tiqq.NewDelete[UserScope](table)
}
func (table UserTableDef) Insert() postgres.InsertQuery[UserScope] {
	return postgres.NewInsert(tiqq.NewInsert[UserScope, tiqq.PostgreSQLMarker](table.ref, []string{"id", "name", "manager_id"}, []string{"id", "name"}, [][]string{{"id"}}))
}
func (table UserTableDef) As(alias string) UserTableDef {
	table.ref = table.ref.As(alias)
	table.ID = tiqq.AliasNumericColumn[UserScope, UserScope](table.ID, alias)
	table.Name = tiqq.AliasColumn[UserScope, UserScope](table.Name, alias)
	table.ManagerID = tiqq.AliasNumericColumn[UserScope, UserScope](table.ManagerID, alias)
	return table
}
