// Code generated by tiqq prototype; DO NOT EDIT.
package schema

import (
	"database/sql"

	"github.com/eji/tiqq"
)

type UserScope struct{}
type AddressScope struct{}
type UserAddressScope struct{}

type UserTableDef struct {
	ID   tiqq.Column[UserScope, int64, int64]
	Name tiqq.Column[UserScope, string, string]
}

type AddressTableDef struct {
	ID      tiqq.Column[AddressScope, int64, int64]
	UserID  tiqq.Column[AddressScope, int64, int64]
	Address tiqq.Column[AddressScope, string, string]
}

var UserTable = UserTableDef{
	ID:   tiqq.RequiredColumn[UserScope, int64]("users", "id"),
	Name: tiqq.RequiredColumn[UserScope, string]("users", "name"),
}

var AddressTable = AddressTableDef{
	ID:      tiqq.RequiredColumn[AddressScope, int64]("addresses", "id"),
	UserID:  tiqq.RequiredColumn[AddressScope, int64]("addresses", "user_id"),
	Address: tiqq.RequiredColumn[AddressScope, string]("addresses", "address"),
}

type joinedUserView struct {
	ID   tiqq.Column[UserAddressScope, int64, int64]
	Name tiqq.Column[UserAddressScope, string, string]
}

type UserAddressJoin struct {
	left   joinedUserView
	right  nullableAddressView
	source tiqq.Source
}

type nullableAddressView struct {
	ID      tiqq.Column[UserAddressScope, sql.Null[int64], int64]
	UserID  tiqq.Column[UserAddressScope, sql.Null[int64], int64]
	Address tiqq.Column[UserAddressScope, sql.Null[string], string]
}

type joinedAddressView struct {
	ID      tiqq.Column[UserAddressScope, int64, int64]
	UserID  tiqq.Column[UserAddressScope, int64, int64]
	Address tiqq.Column[UserAddressScope, string, string]
}

type UserAddressInnerJoin struct {
	left   joinedUserView
	right  joinedAddressView
	source tiqq.Source
}

func (t UserTableDef) LeftJoin(right AddressTableDef, on tiqq.JoinCondition) UserAddressJoin {
	return UserAddressJoin{
		left: joinedUserView{
			ID:   tiqq.RebindRequired[UserScope, UserAddressScope](t.ID),
			Name: tiqq.RebindRequired[UserScope, UserAddressScope](t.Name),
		},
		right: nullableAddressView{
			ID:      tiqq.RebindNullable[AddressScope, UserAddressScope](right.ID),
			UserID:  tiqq.RebindNullable[AddressScope, UserAddressScope](right.UserID),
			Address: tiqq.RebindNullable[AddressScope, UserAddressScope](right.Address),
		},
		source: tiqq.NewLeftJoinSource("users", "addresses", on),
	}
}

func (t UserTableDef) InnerJoin(right AddressTableDef, on tiqq.JoinCondition) UserAddressInnerJoin {
	return UserAddressInnerJoin{
		left: joinedUserView{
			ID:   tiqq.RebindRequired[UserScope, UserAddressScope](t.ID),
			Name: tiqq.RebindRequired[UserScope, UserAddressScope](t.Name),
		},
		right: joinedAddressView{
			ID:      tiqq.RebindRequired[AddressScope, UserAddressScope](right.ID),
			UserID:  tiqq.RebindRequired[AddressScope, UserAddressScope](right.UserID),
			Address: tiqq.RebindRequired[AddressScope, UserAddressScope](right.Address),
		},
		source: tiqq.NewInnerJoinSource("users", "addresses", on),
	}
}

func (j UserAddressJoin) Left() joinedUserView       { return j.left }
func (j UserAddressJoin) Right() nullableAddressView { return j.right }

func (j UserAddressJoin) Where(predicates ...tiqq.Predicate[UserAddressScope]) tiqq.Query[UserAddressScope] {
	return tiqq.NewQuery[UserAddressScope](j.source).Where(predicates...)
}

func (j UserAddressJoin) Select(columns ...tiqq.Selection[UserAddressScope]) tiqq.Query[UserAddressScope] {
	return tiqq.NewQuery[UserAddressScope](j.source).Select(columns...)
}

func (j UserAddressInnerJoin) Left() joinedUserView     { return j.left }
func (j UserAddressInnerJoin) Right() joinedAddressView { return j.right }

func (j UserAddressInnerJoin) Where(predicates ...tiqq.Predicate[UserAddressScope]) tiqq.Query[UserAddressScope] {
	return tiqq.NewQuery[UserAddressScope](j.source).Where(predicates...)
}

func (j UserAddressInnerJoin) Select(columns ...tiqq.Selection[UserAddressScope]) tiqq.Query[UserAddressScope] {
	return tiqq.NewQuery[UserAddressScope](j.source).Select(columns...)
}
